apiVersion: v1
kind: Pod
metadata:
  name: pv-pod2
spec:
  containers:
    - name: pv-container
      image: nginx
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: pv-storage
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim
